# Generated by Django 5.0.6 on 2024-05-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('da_xac_nhan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_xuat_phat', models.CharField(max_length=255)),
                ('diem_den', models.CharField(max_length=255)),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thoi_gian_khoi_hanh', models.DateTimeField()),
                ('nha_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.nhaxe')),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_khoi_hanh', models.DateTimeField()),
                ('so_ve_con_lai', models.IntegerField(default=0)),
                ('tuyen_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.tuyenxe')),
            ],
        ),
    ]
