# Generated by Django 5.0.6 on 2024-05-14 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0002_nhaxe_tuyenxe_chuyenxe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('phuong_thuc_thanh_toan', models.CharField(max_length=100)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('chuyen_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.chuyenxe')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.customuser')),
            ],
        ),
    ]
