# Generated by Django 5.0.6 on 2024-05-15 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nhaxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlynhaxe.nhaxe'),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='khoa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten_nguoi_gui', models.CharField(max_length=100)),
                ('so_dien_thoai_nguoi_gui', models.CharField(max_length=20)),
                ('email_nguoi_gui', models.EmailField(max_length=254)),
                ('ho_ten_nguoi_nhan', models.CharField(max_length=100)),
                ('so_dien_thoai_nguoi_nhan', models.CharField(max_length=20)),
                ('email_nguoi_nhan', models.EmailField(max_length=254)),
                ('thoi_gian_gui', models.DateTimeField()),
                ('thoi_gian_nhan', models.DateTimeField(blank=True, null=True)),
                ('da_gui_email', models.BooleanField(default=False)),
                ('nhaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.nhaxe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nhaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.nhaxe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.customuser')),
            ],
        ),
    ]
