# Generated by Django 5.0.6 on 2024-05-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0004_remove_customuser_avatar_customuser_nhaxe_nhaxe_khoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nhaxe',
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.customuser'),
        ),
    ]
