# Generated by Django 5.0.6 on 2024-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0005_remove_customuser_nhaxe_nhaxe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('garage', 'Garage')], default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='thoi_gian_khoi_hanh',
            field=models.CharField(max_length=255),
        ),
    ]
