# Generated by Django 5.0.6 on 2024-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0006_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ten_khach_hang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
