# Generated by Django 5.0.6 on 2024-05-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlynhaxe', '0007_booking_ten_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chuyen_xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlynhaxe.tuyenxe'),
        ),
    ]
